rvm:
  - 1.9.2
  - 1.9.3
branches:
  only:
    - master
notifications:
  email:
    - joel.azemar@mgmail.com
  on_success: change
  on_failure: always
before_script:
  - "bundle exec rake db:create db:migrate db:test:prepare"
script: "bundle exec rspec spec && bundle exec cucumber"